In [1]:
import numpy as np
import pandas as pd

In [2]:
data=pd.read_csv('Iris.csv')

In [3]:
data.head()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm      Species
0   1            5.1           3.5            1.4           0.2  Iris-setosa
1   2            4.9           3.0            1.4           0.2  Iris-setosa
2   3            4.7           3.2            1.3           0.2  Iris-setosa
3   4            4.6           3.1            1.5           0.2  Iris-setosa
4   5            5.0           3.6            1.4           0.2  Iris-setosa

In [4]:
data.shape

(150, 6)

In [5]:
data['Species'].value_counts()

Iris-setosa        50
Iris-versicolor    50
Iris-virginica     50
Name: Species, dtype: int64

In [6]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 6 columns):
 #   Column         Non-Null Count  Dtype  
---  ------         --------------  -----  
 0   Id             150 non-null    int64  
 1   SepalLengthCm  150 non-null    float64
 2   SepalWidthCm   150 non-null    float64
 3   PetalLengthCm  150 non-null    float64
 4   PetalWidthCm   150 non-null    float64
 5   Species        150 non-null    object 
dtypes: float64(4), int64(1), object(1)
memory usage: 7.2+ KB


In [7]:
data.describe()

Id  SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
count  150.000000     150.000000    150.000000     150.000000    150.000000
mean    75.500000       5.843333      3.054000       3.758667      1.198667
std     43.445368       0.828066      0.433594       1.764420      0.763161
min      1.000000       4.300000      2.000000       1.000000      0.100000
25%     38.250000       5.100000      2.800000       1.600000      0.300000
50%     75.500000       5.800000      3.000000       4.350000      1.300000
75%    112.750000       6.400000      3.300000       5.100000      1.800000
max    150.000000       7.900000      4.400000       6.900000      2.500000

In [8]:
 x=data.iloc[:,1:5]

In [9]:
x.head()

SepalLengthCm  SepalWidthCm  PetalLengthCm  PetalWidthCm
0            5.1           3.5            1.4           0.2
1            4.9           3.0            1.4           0.2
2            4.7           3.2            1.3           0.2
3            4.6           3.1            1.5           0.2
4            5.0           3.6            1.4           0.2

In [12]:
y=data.iloc[:,-1]

In [13]:
y.head()

0    Iris-setosa
1    Iris-setosa
2    Iris-setosa
3    Iris-setosa
4    Iris-setosa
Name: Species, dtype: object

In [14]:
from sklearn.preprocessing import StandardScaler

In [15]:
scaler=StandardScaler()

In [16]:
x=scaler.fit_transform(x)

In [17]:
x[0:5]

array([[-0.90068117,  1.03205722, -1.3412724 , -1.31297673],
       [-1.14301691, -0.1249576 , -1.3412724 , -1.31297673],
       [-1.38535265,  0.33784833, -1.39813811, -1.31297673],
       [-1.50652052,  0.10644536, -1.2844067 , -1.31297673],
       [-1.02184904,  1.26346019, -1.3412724 , -1.31297673]])

In [18]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test =train_test_split(x,y,test_size=0.2)

In [19]:
x_train.shape 

(120, 4)

In [21]:
 from sklearn.neighbors import KNeighborsClassifier

In [22]:
model = KNeighborsClassifier(n_neighbors=1)

In [23]:
model.fit(x_train,y_train)

KNeighborsClassifier(n_neighbors=1)

In [24]:
predicted=model.predict(x_test)

In [25]:
predicted[0:5]

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [26]:
y_test[0:5]

131     Iris-virginica
95     Iris-versicolor
128     Iris-virginica
82     Iris-versicolor
136     Iris-virginica
Name: Species, dtype: object

In [27]:
from sklearn.metrics import accuracy_score
accuracy=accuracy_score(y_test,predicted)

In [28]:
accuracy

1.0

In [30]:
from sklearn.metrics import confusion_matrix

In [31]:
cm=confusion_matrix(y_test,predicted)

In [32]:
cm

array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  0, 12]], dtype=int64)

In [38]:
result = pd.DataFrame(data=[y_test.values,predicted],index=['y_test','predicted'])
result.transpose()

y_test        predicted
0    Iris-virginica   Iris-virginica
1   Iris-versicolor  Iris-versicolor
2    Iris-virginica   Iris-virginica
3   Iris-versicolor  Iris-versicolor
4    Iris-virginica   Iris-virginica
5       Iris-setosa      Iris-setosa
6   Iris-versicolor  Iris-versicolor
7       Iris-setosa      Iris-setosa
8       Iris-setosa      Iris-setosa
9       Iris-setosa      Iris-setosa
10      Iris-setosa      Iris-setosa
11   Iris-virginica   Iris-virginica
12   Iris-virginica   Iris-virginica
13  Iris-versicolor  Iris-versicolor
14  Iris-versicolor  Iris-versicolor
15      Iris-setosa      Iris-setosa
16   Iris-virginica   Iris-virginica
17  Iris-versicolor  Iris-versicolor
18      Iris-setosa      Iris-setosa
19   Iris-virginica   Iris-virginica
20  Iris-versicolor  Iris-versicolor
21      Iris-setosa      Iris-setosa
22  Iris-versicolor  Iris-versicolor
23      Iris-setosa      Iris-setosa
24   Iris-virginica   Iris-virginica
25   Iris-virginica   Iris-virginica
26      Iris-setosa      Iris-setosa
27   Iris-virginica   Iris-virginica
28   Iris-virginica   Iris-virginica
29   Iris-virginica   Iris-virginica

In [42]:
correct_sum=[]

In [44]:
for i in range (1,20):
    model=KNeighborsClassifier(n_neighbors=i)
    model.fit(x_train,y_train)
    predicted=model.predict(x_test)
    correct=np.sum(predicted==y_test)
    correct_sum.append(correct)

In [45]:
correct_sum

[30, 28, 28, 28, 29, 28, 28, 28, 28, 28, 28, 28, 29, 28, 30, 30, 30, 30, 30]

In [46]:
result=pd.DataFrame(data=correct_sum)
result.index=result.index+1

In [47]:
result.T

1   2   3   4   5   6   7   8   9   10  11  12  13  14  15  16  17  18  19
0  30  28  28  28  29  28  28  28  28  28  28  28  29  28  30  30  30  30  30

In [48]:
model = KNeighborsClassifier(n_neighbors=10)
model.fit(x_train,y_train)
predicted=model.predict(x_test)
predicted[0:10]

array(['Iris-virginica', 'Iris-versicolor', 'Iris-virginica',
       'Iris-versicolor', 'Iris-virginica', 'Iris-setosa',
       'Iris-versicolor', 'Iris-setosa', 'Iris-setosa', 'Iris-setosa'],
      dtype=object)

In [49]:
accuracy_score(y_test,predicted)

0.9333333333333333

In [50]:
confusion_matrix(y_test,predicted)


array([[10,  0,  0],
       [ 0,  8,  0],
       [ 0,  2, 10]], dtype=int64)